
-- NEXUS LABEL - EXTENSION SCHEMA RESOURCES
ALTER TABLE resources ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS instagram text;
